name: release

on:
  push:
    branches: 
      - dev

permissions:
  id-token: write
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-node@v4
        with: 
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm@latest
      - run: bun install
      - id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
